version: "3"

services:
  proxy:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    ports:
      - "80:80"
  was:
    build:
      context: .
      dockerfile: ./tomcat/dockerfile
      voluemse :
        - www:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
