version: "3"

services:
  proxy:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    ports:
      - "80:80"
  was:
    build:
      context: .
      dockerfile: ./tomcat/dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./www:/usr/local/tomcat/webapps
  jenkins:
    build:
      context: .
      dockerfile: ./jenkins/dockerfile
    ports:
      - "3030:8080:
